"""initial_supabase_schema

Revision ID: 17cb7593c420
Revises: 
Create Date: 2026-10-04 08:05:40.346263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cb7593c420'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_code', sa.String(length=64), nullable=False),
    sa.Column('camera_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_code'), 'cameras', ['camera_code'], unique=True)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('college_vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_name', sa.String(length=128), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_vehicles_id'), 'college_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_college_vehicles_vehicle_number'), 'college_vehicles', ['vehicle_number'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_category', sa.String(length=32), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('total_sightings', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    op.create_table('recognition_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('college_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_category', sa.String(length=32), nullable=False),
    sa.Column('vehicle_name', sa.String(length=128), nullable=True),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('yolo_confidence', sa.Float(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=False),
    sa.Column('vehicle_image_path', sa.String(length=512), nullable=True),
    sa.Column('plate_image_path', sa.String(length=512), nullable=True),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('frames_observed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_vehicle_id'], ['college_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recognition_events_camera_id'), 'recognition_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_recognition_events_id'), 'recognition_events', ['id'], unique=False)
    op.create_index(op.f('ix_recognition_events_movement_type'), 'recognition_events', ['movement_type'], unique=False)
    op.create_index(op.f('ix_recognition_events_plate_number'), 'recognition_events', ['plate_number'], unique=False)
    op.create_index(op.f('ix_recognition_events_vehicle_category'), 'recognition_events', ['vehicle_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recognition_events_vehicle_category'), table_name='recognition_events')
    op.drop_index(op.f('ix_recognition_events_plate_number'), table_name='recognition_events')
    op.drop_index(op.f('ix_recognition_events_movement_type'), table_name='recognition_events')
    op.drop_index(op.f('ix_recognition_events_id'), table_name='recognition_events')
    op.drop_index(op.f('ix_recognition_events_camera_id'), table_name='recognition_events')
    op.drop_table('recognition_events')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_college_vehicles_vehicle_number'), table_name='college_vehicles')
    op.drop_index(op.f('ix_college_vehicles_id'), table_name='college_vehicles')
    op.drop_table('college_vehicles')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_code'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
